export const impressive_brand = [
  "Brand Strategy",
  "Brand Positioning",
  "Brand Architecture",
  "Brand Audit",
  "Brand Naming",
  "Content Framework",
  "Identity (Logo Design)",
  "Design System",
  "Brand Guidelines",
  "Voice and Tone",
  "Copywriting",
  "Video Production",
  "Packaging Design",
  "Presentations",
  "Animation",
  "Brochures",
  "Brand Management",
];

export const interactive_digital = [
  "User Experience Design",
  "Web Design and Development",
  "Web Applications",
  "E-commerce Portals",
  "Cyber Security",
  "Website Maintenance and AMC",
  "Creating Innovative Ideas",
  "Product and Market Strategy",
  "Mobile App Development",
  "UI/ UX Design",
  "VR Software Development",
  "AR App Development",
  "Mixed Reality",
  "3D Design and Modelling",
];

export const effective_communication = [
  "Digital Strategy",
  "Brand Audit",
  "Market Research",
  "Campaign Implementation",
  "Social Media Ads",
  "Community Management",
  "Website Optimisation",
  "Targeted SEO ads",
  "Audience Insights",
];
